service: astrobin-ng

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  timeout: 30
  stage: production
  region: us-east-1

package:
  exclude:
    - src/**
    - node_modules/**
    - e2e/**
    - coverage/**
    - '!node_modules/aws-serverless-express/**'
    - '!node_modules/binary-case/**'
    - '!node_modules/type-is/**'
    - '!node_modules/media-typer/**'
    - '!node_modules/mime-types/**'
    - '!node_modules/mime-db/**'
    - '!node_modules/@vendia/**'


custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: lambda.ssrserverless
    events:
      - http: ANY {proxy+}
      - http: ANY /
